/**
 * Resend 邮件发送模块
 * 使用 Resend API 从 hi@scoutai.cc 发信
 * 支持中文/英文双语言模板
 */
import { Resend } from "resend";
import type { DailyDigest } from "./types.js";

function buildHtml(digest: DailyDigest, topStory: string, editorNote: string, lang: "zh" | "en" = "zh"): string {
  const isEN = lang === "en";

  const labels = {
    title: isEN ? "🤖 AI Frontier Daily" : "🤖 AI 前沿日报",
    subtitle: isEN
      ? `${digest.date} · Curated 5-8 items daily`
      : `${digest.date} · 每日精选 5-8 条`,
    topStoryLabel: isEN ? "📌 Today's Top Story" : "📌 今日头条",
    editorLabel: "✏️",
    papers: isEN ? "Research Papers" : "前沿论文",
    trending: isEN ? "Trending Posts" : "技术热帖",
    tools: isEN ? "Open Source Tools" : "开源工具",
    news: isEN ? "Industry News" : "行业新闻",
    footer: isEN
      ? `Generated by <a href="https://scoutai.cc" style="color:#2563eb">AI Scout</a> · Delivered daily at 8:00 (Beijing Time)`
      : `由 <a href="https://scoutai.cc" style="color:#2563eb">AI 情报参谋</a> 自动生成 · 每天 8:00 (北京时间) 发送`,
  };

  const section = (
    icon: string,
    title: string,
    items: { title: string; url: string; summary: string }[]
  ): string => {
    if (items.length === 0) return "";
    const rows = items
      .map(
        (item) =>
          `<tr>
            <td style="padding:12px 0;border-bottom:1px solid #eee">
              <a href="${item.url}" style="color:#2563eb;font-weight:600;text-decoration:none;font-size:15px">${item.title}</a>
              <p style="color:#666;margin:4px 0 0;font-size:13px;line-height:1.5">${item.summary}</p>
            </td>
          </tr>`
      )
      .join("");
    return `
      <h2 style="color:#1a1a2e;margin:24px 0 12px;font-size:18px;border-left:4px solid #2563eb;padding-left:10px">${icon} ${title}</h2>
      <table style="width:100%;border-collapse:collapse">${rows}</table>
    `;
  };

  return `<!DOCTYPE html>
<html lang="${isEN ? "en" : "zh-CN"}">
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;padding:20px;background:#f8f9fa">
  <div style="background:#fff;border-radius:12px;padding:30px;box-shadow:0 2px 8px rgba(0,0,0,.06)">
    <div style="text-align:center;padding-bottom:20px;border-bottom:2px solid #2563eb">
      <h1 style="color:#1a1a2e;margin:0;font-size:24px">${labels.title}</h1>
      <p style="color:#999;margin:6px 0 0;font-size:13px">${labels.subtitle}</p>
    </div>
    <div style="background:linear-gradient(135deg,#2563eb,#1d4ed8);color:#fff;border-radius:8px;padding:16px 20px;margin-top:20px">
      <p style="margin:0;font-size:13px;opacity:.8">${labels.topStoryLabel}</p>
      <p style="margin:6px 0 0;font-size:15px;font-weight:500;line-height:1.5">${topStory}</p>
    </div>
    <div style="background:#fef3c7;border:1px solid #fcd34d;border-radius:8px;padding:12px 16px;margin-top:8px">
      <p style="margin:0;font-size:13px;color:#92400e">${labels.editorLabel} ${editorNote}</p>
    </div>
    ${section("📄", labels.papers, digest.papers)}
    ${section("🔥", labels.trending, digest.trending)}
    ${section("🛠", labels.tools, digest.tools)}
    ${section("📰", labels.news, digest.news)}
    <div style="margin-top:30px;padding-top:16px;border-top:1px solid #eee;text-align:center">
      <p style="color:#999;font-size:11px;margin:0">${labels.footer}</p>
    </div>
  </div>
</body></html>`;
}

export async function sendEmail(
  digest: DailyDigest,
  topStory: string,
  editorNote: string,
  resendApiKey: string,
  toEmail: string,
  lang: "zh" | "en" = "zh"
): Promise<boolean> {
  if (!resendApiKey || resendApiKey.length < 10) {
    console.error("❌ Resend API Key 未配置");
    return false;
  }

  const subject = lang === "en"
    ? `🤖 AI Frontier Daily | ${digest.date}`
    : `🤖 AI 前沿日报 | ${digest.date}`;

  try {
    const resend = new Resend(resendApiKey);

    const { data, error } = await resend.emails.send({
      from: "AI Scout <hi@scoutai.cc>",
      to: [toEmail],
      subject,
      html: buildHtml(digest, topStory, editorNote, lang),
    });

    if (error) {
      console.error("  [resend] 发送失败:", error);
      return false;
    }

    console.error("  [resend] 发送成功! ID:", data?.id);
    return true;
  } catch (error: any) {
    console.error("  [resend] 发送失败:", error.message || error);
    return false;
  }
}
